
redis:
  host: '121.37.171.89'
  port: 6379
  password: '123456zax'
  db: 1

fastapi:
  host: '0.0.0.0'
  port: 8001

scheduler:
  verifier_interval: 30
  fetch_interval: 60
  verifier_url: 'http://www.baidu.com/'
  proxy_pool_name: 'proxypool'
  logger_name: 'app.log'
